version: '3.9'
services:
  frontend:
    build: ./agni-frontend
    image: agni-network-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./agni-frontend:/app
      - /app/node_modules  # This prevents node_modules from being overwritten
    command: npm run dev
    depends_on:
      - backend
  backend:
    build: ./agni-backend
    ports:
      - "5000:5000"
    volumes:
      - ./agni-backend:/app
    command: python app.py